require_relative '../bibliotecas/Box'
require_relative '../bibliotecas/Falcon'
require_relative '../bibliotecas/GameObject'
require_relative '../bibliotecas/GUIText'
require_relative '../bibliotecas/Hiero'
require_relative '../bibliotecas/Janela'
require_relative '../bibliotecas/Sprite'
require 'gosu'